print("Program starting.")
print("Estimate how many minutes you spent on programming...")
print()
T1 = int(input("A1_T1: "))
T2 = int(input("A1_T2: "))
T3 = int(input("A1_T3: "))
T4 = int(input("A1_T4: "))
T5 = int(input("A1_T5: "))
T6 = int(input("A1_T6: "))
T7 = int(input("A1_T7: "))
Summa = int(T1+T2+T3+T4+T5+T6+T7)
Keskiarvo = float(Summa/7)
print()
print("In total you spent ", Summa, "minutes on programming.")
print("Average per task was", (round(Keskiarvo,2)), "minutes and same rounded to the nearest integer", (round(Keskiarvo)), "min.")
print()
print("Program ending.")