print("Program starting.")
Word = input("Insert a closed compound word: ")
Length = len(Word)
Last = Word[-1]
print("The word you inserted is '", Word, "' and in reverse it is '", (Word[::-1]), "'", sep='')
print("The inserted word length is", Length)
print("Last character is '", Last, "'", sep='')
print("Take substring from the inserted word by inserting...")
start = int(input("1) Starting point: "))
end = int(input("2) Ending point: "))
step = int(input("3) Step size: "))
substring = (Word[start:end:step])
print("The word '", Word, "' sliced to the defined substring is '", substring, "'.", sep='')
print("Program ending.")
